services:
  django-app:
    image: sinatra
    container_name: sinatra-django
    ports:
      - "8000:8000"  # Make sure this is present
    expose:
      - "8000"  # Optional: Makes it available to linked services
    environment:
      - DEBUG=1
    command: gunicorn Sinatra.wsgi:application --bind 0.0.0.0:8000
