# Generated by Django 5.1.6 on 2025-02-23 03:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=50)),
                ('type', models.CharField(choices=[('NGO', 'NGO'), ('Charity', 'Charity')], default='Charity', max_length=50)),
                ('address', models.CharField(default='', max_length=50)),
                ('address_line_one', models.CharField(default='', max_length=50)),
                ('address_line_two', models.CharField(default='', max_length=50)),
                ('address_line_county', models.CharField(default='', max_length=50)),
                ('address_line_city', models.CharField(default='', max_length=50)),
                ('address_line_postcode', models.CharField(default='', max_length=20)),
            ],
        ),
    ]
