# Generated by Django 5.1.6 on 2025-02-23 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organisation', '0002_organisation_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation',
            name='created_by',
        ),
    ]
