# Generated by Django 5.1.6 on 2025-02-22 21:35

from django.db import migrations

def create_skills(apps):
    Skill = apps.get_model('skills', 'Skill')
    
    skills_data = {
        'Educational Skills': [
            'Math Tutoring',
            'Science Tutoring',
            'English Tutoring',
            'Spanish Language Teaching',
            'French Language Teaching',
        ],
        'Technical Skills': [
            'IT Support',
            'Photography',
            'Videography',
            'Coding/Programming Tutoring',

        ],
        'Community & Social Skills': [
            'Elderly Care & Companionship',
            'Babysitting/Childcare',
        ],
        'Logistics & Transport Skills': [
            'Driving Services',
            'Delivery Assistance',
            'Moving & Packing Assistance',
        ],
        'Environmental Skills': [
            'Recycling & Waste Management',
            'Renewable Energy Guidance',
            'Community Cleanup Organization',
        ],
    }

    # Create all skills
    for category, skills in skills_data.items():
        for skill_name in skills:
            Skill.objects.create(name=skill_name, category=category)

def delete_skills(apps):
    Skill = apps.get_model('skills', 'Skill')
    Skill.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]
    operations = [ migrations.RunPython(create_skills),
    ]
