# Generated by Django 5.1.6 on 2025-02-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
