# Generated by Django 5.1.6 on 2025-02-23 03:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_populate_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
